### PR TITLE
use '-y' for apt-get install

### PR DESCRIPTION
**Pull request by eddelbuettel**
As discussed, a minimal PR to add `-y` for Ubuntu trusty. It will still work for precise.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Sorry, I had to add the second commit to make Travis pass.  You have to undo that again at your end or do whatever your do.  This never worked for me as the two subjects for OS X always balk.

**Comment by craigcitro** [comment]
so the OSX failure was strange (it was just a timeout); it doesn't get triggered that often, so i wonder if it's gotten too long in the tooth, or if it always works a second time due to caching?

LGTM, but let's keep the OSX tests for now (so maybe drop the second commit)?

**Comment by eddelbuettel** [comment]
Feel free to cherry pick.

**Comment by eddelbuettel** [comment]
I still think you should merge this now and re-enable the currently-commented-out part (which I also have commented out iny main branch, not sure what is going on there and not particularly motivated to chase an archicture on which I do not have shell access anywhere) as the migration plan [outlined by the Travis folks in this blog post](https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future) will lead to rather massive failures.

**Comment by craigcitro** [comment]
good call (was leaving this until tonight, but dont' want to break people)

**Comment by eddelbuettel** [comment]
And sorry about the semi-unrelated second commit ... but OCD makes me only create pull requests 'in green'.

**Pull request merged**
